apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-pod-goku-nodejs
spec:
  type: NodePort
  selector:
    app: label-pod-goku-nodejs
  ports:
  - port: 3000
    nodePort: 30001 #ate 32767 


